version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=website25
    volumes:
      - /home/gabriel/Desktop/react_rails/tmp/db:/var/lib/mysql/
    ports:
      - "4206:4206"
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - /home/gabriel/Desktop/react_rails:/thisapp
    ports:
      - '3035:3035'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /home/gabriel/Desktop/react_rails:/thisapp
    ports:
      - "3000:3000"
    depends_on:
      - db